apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: groq-chatbot-pipeline
spec:
  params:
    - name: git-repo
      type: string
      default: "https://github.com/SyedArmghanAhmad/Openshift-implementations.git"
    - name: image-name
      type: string
      default: "groq-chatbot"

  tasks:
    - name: build
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/armghan18/$(params.image-name)"
        - name: DOCKERFILE
          value: "app/Dockerfile"
        - name: CONTEXT
          value: "app"

    - name: deploy-dev
      taskRef:
        name: openshift-client
      runAfter: ["build"]
      params:
        - name: SCRIPT
          value: |
            oc apply -f openshift/deployment-dev.yaml
            oc apply -f openshift/route-dev.yaml

    - name: approve-uat
      taskRef:
        name: approval-task
      runAfter: ["deploy-dev"]
      params:
        - name: MESSAGE
          value: "Approve UAT deployment?"

    - name: promote-uat
      taskRef:
        name: openshift-client
      runAfter: ["approve-uat"]
      params:
        - name: SCRIPT
          value: |
            oc tag groq-chatbot:latest groq-chatbot:stable
            oc apply -f openshift/deployment-uat.yaml
            oc apply -f openshift/route-uat.yaml

    - name: approve-prod
      taskRef:
        name: approval-task
      runAfter: ["promote-uat"]

    - name: promote-prod
      taskRef:
        name: openshift-client
      runAfter: ["approve-prod"]
      params:
        - name: SCRIPT
          value: |
            oc apply -f openshift/deployment-prod.yaml
            oc apply -f openshift/route-prod.yaml