# route-dev.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: groq-chatbot-dev
spec:
  host: dev-chatbot-armghan18.apps.yourcluster.com
  to:
    kind: Deployment
    name: groq-chatbot-dev

# route-uat.yaml (similar for UAT/PROD)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: groq-chatbot-uat
spec:
  host: uat-chatbot-armghan18.apps.yourcluster.com
  to:
    kind: Deployment
    name: groq-chatbot-uat